---
- name: Disable SQL Entension Task Scheduled
  hosts: windows
  tasks:
    - name: Esegui comando PowerShell
      win_shell: |
        Disable-ScheduledTask -TaskName "SqlServerExtensionPermissionProvider" -TaskPath "\Microsoft\SqlServerExtension""
